# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # config.vm.network :private_network, ip: "192.168.33.10"
  # config.vm.network :public_network
  # config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    # vgrnt-test is hardcoded in util-spec.rb
    vb.name = "vgrnt-test"

    vb.customize ["modifyvm", :id, "--memory", "128"]
  end

end
