# -*- mode: ruby -*-
# vi: set ft=ruby :

# Fixture::neveron - all the tests will assume that we never turn on this fixture

Vagrant.configure('2') do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
end
